# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        /post/:title

# Setup
title:            "umr4n6"
description:      "Personal blog about this and that"
url:              http://umr4n6.github.io
baseurl:          "/"

author:
  name:           "umr4n6"

# Custom vars
twitter:        https://twitter.com/umr4n6

